// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fCommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fCommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fCommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fCommon_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fCommon_2eproto;
namespace Proto {
namespace Common {
class CameraProto;
class CameraProtoDefaultTypeInternal;
extern CameraProtoDefaultTypeInternal _CameraProto_default_instance_;
class EngineData;
class EngineDataDefaultTypeInternal;
extern EngineDataDefaultTypeInternal _EngineData_default_instance_;
class LightProto;
class LightProtoDefaultTypeInternal;
extern LightProtoDefaultTypeInternal _LightProto_default_instance_;
class ObjectProto;
class ObjectProtoDefaultTypeInternal;
extern ObjectProtoDefaultTypeInternal _ObjectProto_default_instance_;
class ShaderProto;
class ShaderProtoDefaultTypeInternal;
extern ShaderProtoDefaultTypeInternal _ShaderProto_default_instance_;
class TextureProto;
class TextureProtoDefaultTypeInternal;
extern TextureProtoDefaultTypeInternal _TextureProto_default_instance_;
}  // namespace Common
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::Common::CameraProto* Arena::CreateMaybeMessage<::Proto::Common::CameraProto>(Arena*);
template<> ::Proto::Common::EngineData* Arena::CreateMaybeMessage<::Proto::Common::EngineData>(Arena*);
template<> ::Proto::Common::LightProto* Arena::CreateMaybeMessage<::Proto::Common::LightProto>(Arena*);
template<> ::Proto::Common::ObjectProto* Arena::CreateMaybeMessage<::Proto::Common::ObjectProto>(Arena*);
template<> ::Proto::Common::ShaderProto* Arena::CreateMaybeMessage<::Proto::Common::ShaderProto>(Arena*);
template<> ::Proto::Common::TextureProto* Arena::CreateMaybeMessage<::Proto::Common::TextureProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {
namespace Common {

// ===================================================================

class EngineData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.EngineData) */ {
 public:
  inline EngineData() : EngineData(nullptr) {}
  virtual ~EngineData();

  EngineData(const EngineData& from);
  EngineData(EngineData&& from) noexcept
    : EngineData() {
    *this = ::std::move(from);
  }

  inline EngineData& operator=(const EngineData& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineData& operator=(EngineData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EngineData& default_instance();

  static inline const EngineData* internal_default_instance() {
    return reinterpret_cast<const EngineData*>(
               &_EngineData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EngineData& a, EngineData& b) {
    a.Swap(&b);
  }
  inline void Swap(EngineData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EngineData* New() const final {
    return CreateMaybeMessage<EngineData>(nullptr);
  }

  EngineData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EngineData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EngineData& from);
  void MergeFrom(const EngineData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EngineData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.EngineData";
  }
  protected:
  explicit EngineData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectFieldNumber = 2,
    kCameraFieldNumber = 1,
  };
  // repeated .Proto.Common.ObjectProto object = 2;
  int object_size() const;
  private:
  int _internal_object_size() const;
  public:
  void clear_object();
  ::Proto::Common::ObjectProto* mutable_object(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::ObjectProto >*
      mutable_object();
  private:
  const ::Proto::Common::ObjectProto& _internal_object(int index) const;
  ::Proto::Common::ObjectProto* _internal_add_object();
  public:
  const ::Proto::Common::ObjectProto& object(int index) const;
  ::Proto::Common::ObjectProto* add_object();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::ObjectProto >&
      object() const;

  // .Proto.Common.CameraProto camera = 1;
  bool has_camera() const;
  private:
  bool _internal_has_camera() const;
  public:
  void clear_camera();
  const ::Proto::Common::CameraProto& camera() const;
  ::Proto::Common::CameraProto* release_camera();
  ::Proto::Common::CameraProto* mutable_camera();
  void set_allocated_camera(::Proto::Common::CameraProto* camera);
  private:
  const ::Proto::Common::CameraProto& _internal_camera() const;
  ::Proto::Common::CameraProto* _internal_mutable_camera();
  public:
  void unsafe_arena_set_allocated_camera(
      ::Proto::Common::CameraProto* camera);
  ::Proto::Common::CameraProto* unsafe_arena_release_camera();

  // @@protoc_insertion_point(class_scope:Proto.Common.EngineData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::ObjectProto > object_;
  ::Proto::Common::CameraProto* camera_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// -------------------------------------------------------------------

class CameraProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.CameraProto) */ {
 public:
  inline CameraProto() : CameraProto(nullptr) {}
  virtual ~CameraProto();

  CameraProto(const CameraProto& from);
  CameraProto(CameraProto&& from) noexcept
    : CameraProto() {
    *this = ::std::move(from);
  }

  inline CameraProto& operator=(const CameraProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraProto& operator=(CameraProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CameraProto& default_instance();

  static inline const CameraProto* internal_default_instance() {
    return reinterpret_cast<const CameraProto*>(
               &_CameraProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CameraProto& a, CameraProto& b) {
    a.Swap(&b);
  }
  inline void Swap(CameraProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CameraProto* New() const final {
    return CreateMaybeMessage<CameraProto>(nullptr);
  }

  CameraProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CameraProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CameraProto& from);
  void MergeFrom(const CameraProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CameraProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.CameraProto";
  }
  protected:
  explicit CameraProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Proto.Common.CameraProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// -------------------------------------------------------------------

class ShaderProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.ShaderProto) */ {
 public:
  inline ShaderProto() : ShaderProto(nullptr) {}
  virtual ~ShaderProto();

  ShaderProto(const ShaderProto& from);
  ShaderProto(ShaderProto&& from) noexcept
    : ShaderProto() {
    *this = ::std::move(from);
  }

  inline ShaderProto& operator=(const ShaderProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShaderProto& operator=(ShaderProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ShaderProto& default_instance();

  static inline const ShaderProto* internal_default_instance() {
    return reinterpret_cast<const ShaderProto*>(
               &_ShaderProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ShaderProto& a, ShaderProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ShaderProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShaderProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ShaderProto* New() const final {
    return CreateMaybeMessage<ShaderProto>(nullptr);
  }

  ShaderProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ShaderProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ShaderProto& from);
  void MergeFrom(const ShaderProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShaderProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.ShaderProto";
  }
  protected:
  explicit ShaderProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
  };
  // uint32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::uint32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Common.ShaderProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 x_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// -------------------------------------------------------------------

class TextureProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.TextureProto) */ {
 public:
  inline TextureProto() : TextureProto(nullptr) {}
  virtual ~TextureProto();

  TextureProto(const TextureProto& from);
  TextureProto(TextureProto&& from) noexcept
    : TextureProto() {
    *this = ::std::move(from);
  }

  inline TextureProto& operator=(const TextureProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextureProto& operator=(TextureProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TextureProto& default_instance();

  static inline const TextureProto* internal_default_instance() {
    return reinterpret_cast<const TextureProto*>(
               &_TextureProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TextureProto& a, TextureProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TextureProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TextureProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TextureProto* New() const final {
    return CreateMaybeMessage<TextureProto>(nullptr);
  }

  TextureProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TextureProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TextureProto& from);
  void MergeFrom(const TextureProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TextureProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.TextureProto";
  }
  protected:
  explicit TextureProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
  };
  // uint32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::uint32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Common.TextureProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 x_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// -------------------------------------------------------------------

class ObjectProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.ObjectProto) */ {
 public:
  inline ObjectProto() : ObjectProto(nullptr) {}
  virtual ~ObjectProto();

  ObjectProto(const ObjectProto& from);
  ObjectProto(ObjectProto&& from) noexcept
    : ObjectProto() {
    *this = ::std::move(from);
  }

  inline ObjectProto& operator=(const ObjectProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectProto& operator=(ObjectProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ObjectProto& default_instance();

  static inline const ObjectProto* internal_default_instance() {
    return reinterpret_cast<const ObjectProto*>(
               &_ObjectProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ObjectProto& a, ObjectProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObjectProto* New() const final {
    return CreateMaybeMessage<ObjectProto>(nullptr);
  }

  ObjectProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObjectProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ObjectProto& from);
  void MergeFrom(const ObjectProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.ObjectProto";
  }
  protected:
  explicit ObjectProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextureFieldNumber = 2,
    kShaderFieldNumber = 1,
  };
  // repeated .Proto.Common.TextureProto texture = 2;
  int texture_size() const;
  private:
  int _internal_texture_size() const;
  public:
  void clear_texture();
  ::Proto::Common::TextureProto* mutable_texture(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::TextureProto >*
      mutable_texture();
  private:
  const ::Proto::Common::TextureProto& _internal_texture(int index) const;
  ::Proto::Common::TextureProto* _internal_add_texture();
  public:
  const ::Proto::Common::TextureProto& texture(int index) const;
  ::Proto::Common::TextureProto* add_texture();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::TextureProto >&
      texture() const;

  // .Proto.Common.ShaderProto shader = 1;
  bool has_shader() const;
  private:
  bool _internal_has_shader() const;
  public:
  void clear_shader();
  const ::Proto::Common::ShaderProto& shader() const;
  ::Proto::Common::ShaderProto* release_shader();
  ::Proto::Common::ShaderProto* mutable_shader();
  void set_allocated_shader(::Proto::Common::ShaderProto* shader);
  private:
  const ::Proto::Common::ShaderProto& _internal_shader() const;
  ::Proto::Common::ShaderProto* _internal_mutable_shader();
  public:
  void unsafe_arena_set_allocated_shader(
      ::Proto::Common::ShaderProto* shader);
  ::Proto::Common::ShaderProto* unsafe_arena_release_shader();

  // @@protoc_insertion_point(class_scope:Proto.Common.ObjectProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::TextureProto > texture_;
  ::Proto::Common::ShaderProto* shader_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// -------------------------------------------------------------------

class LightProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.Common.LightProto) */ {
 public:
  inline LightProto() : LightProto(nullptr) {}
  virtual ~LightProto();

  LightProto(const LightProto& from);
  LightProto(LightProto&& from) noexcept
    : LightProto() {
    *this = ::std::move(from);
  }

  inline LightProto& operator=(const LightProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline LightProto& operator=(LightProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LightProto& default_instance();

  static inline const LightProto* internal_default_instance() {
    return reinterpret_cast<const LightProto*>(
               &_LightProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LightProto& a, LightProto& b) {
    a.Swap(&b);
  }
  inline void Swap(LightProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LightProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LightProto* New() const final {
    return CreateMaybeMessage<LightProto>(nullptr);
  }

  LightProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LightProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LightProto& from);
  void MergeFrom(const LightProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LightProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.Common.LightProto";
  }
  protected:
  explicit LightProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fCommon_2eproto);
    return ::descriptor_table_proto_2fCommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // uint32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::uint32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 y = 2;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::uint32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 z = 3;
  void clear_z();
  ::PROTOBUF_NAMESPACE_ID::uint32 z() const;
  void set_z(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_z() const;
  void _internal_set_z(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Proto.Common.LightProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 x_;
  ::PROTOBUF_NAMESPACE_ID::uint32 y_;
  ::PROTOBUF_NAMESPACE_ID::uint32 z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fCommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EngineData

// .Proto.Common.CameraProto camera = 1;
inline bool EngineData::_internal_has_camera() const {
  return this != internal_default_instance() && camera_ != nullptr;
}
inline bool EngineData::has_camera() const {
  return _internal_has_camera();
}
inline void EngineData::clear_camera() {
  if (GetArena() == nullptr && camera_ != nullptr) {
    delete camera_;
  }
  camera_ = nullptr;
}
inline const ::Proto::Common::CameraProto& EngineData::_internal_camera() const {
  const ::Proto::Common::CameraProto* p = camera_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Common::CameraProto&>(
      ::Proto::Common::_CameraProto_default_instance_);
}
inline const ::Proto::Common::CameraProto& EngineData::camera() const {
  // @@protoc_insertion_point(field_get:Proto.Common.EngineData.camera)
  return _internal_camera();
}
inline void EngineData::unsafe_arena_set_allocated_camera(
    ::Proto::Common::CameraProto* camera) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(camera_);
  }
  camera_ = camera;
  if (camera) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Common.EngineData.camera)
}
inline ::Proto::Common::CameraProto* EngineData::release_camera() {
  
  ::Proto::Common::CameraProto* temp = camera_;
  camera_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::Common::CameraProto* EngineData::unsafe_arena_release_camera() {
  // @@protoc_insertion_point(field_release:Proto.Common.EngineData.camera)
  
  ::Proto::Common::CameraProto* temp = camera_;
  camera_ = nullptr;
  return temp;
}
inline ::Proto::Common::CameraProto* EngineData::_internal_mutable_camera() {
  
  if (camera_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::Common::CameraProto>(GetArena());
    camera_ = p;
  }
  return camera_;
}
inline ::Proto::Common::CameraProto* EngineData::mutable_camera() {
  // @@protoc_insertion_point(field_mutable:Proto.Common.EngineData.camera)
  return _internal_mutable_camera();
}
inline void EngineData::set_allocated_camera(::Proto::Common::CameraProto* camera) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete camera_;
  }
  if (camera) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(camera);
    if (message_arena != submessage_arena) {
      camera = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, camera, submessage_arena);
    }
    
  } else {
    
  }
  camera_ = camera;
  // @@protoc_insertion_point(field_set_allocated:Proto.Common.EngineData.camera)
}

// repeated .Proto.Common.ObjectProto object = 2;
inline int EngineData::_internal_object_size() const {
  return object_.size();
}
inline int EngineData::object_size() const {
  return _internal_object_size();
}
inline void EngineData::clear_object() {
  object_.Clear();
}
inline ::Proto::Common::ObjectProto* EngineData::mutable_object(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.Common.EngineData.object)
  return object_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::ObjectProto >*
EngineData::mutable_object() {
  // @@protoc_insertion_point(field_mutable_list:Proto.Common.EngineData.object)
  return &object_;
}
inline const ::Proto::Common::ObjectProto& EngineData::_internal_object(int index) const {
  return object_.Get(index);
}
inline const ::Proto::Common::ObjectProto& EngineData::object(int index) const {
  // @@protoc_insertion_point(field_get:Proto.Common.EngineData.object)
  return _internal_object(index);
}
inline ::Proto::Common::ObjectProto* EngineData::_internal_add_object() {
  return object_.Add();
}
inline ::Proto::Common::ObjectProto* EngineData::add_object() {
  // @@protoc_insertion_point(field_add:Proto.Common.EngineData.object)
  return _internal_add_object();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::ObjectProto >&
EngineData::object() const {
  // @@protoc_insertion_point(field_list:Proto.Common.EngineData.object)
  return object_;
}

// -------------------------------------------------------------------

// CameraProto

// -------------------------------------------------------------------

// ShaderProto

// uint32 x = 1;
inline void ShaderProto::clear_x() {
  x_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShaderProto::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShaderProto::x() const {
  // @@protoc_insertion_point(field_get:Proto.Common.ShaderProto.x)
  return _internal_x();
}
inline void ShaderProto::_internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  x_ = value;
}
inline void ShaderProto::set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Proto.Common.ShaderProto.x)
}

// -------------------------------------------------------------------

// TextureProto

// uint32 x = 1;
inline void TextureProto::clear_x() {
  x_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TextureProto::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TextureProto::x() const {
  // @@protoc_insertion_point(field_get:Proto.Common.TextureProto.x)
  return _internal_x();
}
inline void TextureProto::_internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  x_ = value;
}
inline void TextureProto::set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Proto.Common.TextureProto.x)
}

// -------------------------------------------------------------------

// ObjectProto

// .Proto.Common.ShaderProto shader = 1;
inline bool ObjectProto::_internal_has_shader() const {
  return this != internal_default_instance() && shader_ != nullptr;
}
inline bool ObjectProto::has_shader() const {
  return _internal_has_shader();
}
inline void ObjectProto::clear_shader() {
  if (GetArena() == nullptr && shader_ != nullptr) {
    delete shader_;
  }
  shader_ = nullptr;
}
inline const ::Proto::Common::ShaderProto& ObjectProto::_internal_shader() const {
  const ::Proto::Common::ShaderProto* p = shader_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Common::ShaderProto&>(
      ::Proto::Common::_ShaderProto_default_instance_);
}
inline const ::Proto::Common::ShaderProto& ObjectProto::shader() const {
  // @@protoc_insertion_point(field_get:Proto.Common.ObjectProto.shader)
  return _internal_shader();
}
inline void ObjectProto::unsafe_arena_set_allocated_shader(
    ::Proto::Common::ShaderProto* shader) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(shader_);
  }
  shader_ = shader;
  if (shader) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.Common.ObjectProto.shader)
}
inline ::Proto::Common::ShaderProto* ObjectProto::release_shader() {
  
  ::Proto::Common::ShaderProto* temp = shader_;
  shader_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Proto::Common::ShaderProto* ObjectProto::unsafe_arena_release_shader() {
  // @@protoc_insertion_point(field_release:Proto.Common.ObjectProto.shader)
  
  ::Proto::Common::ShaderProto* temp = shader_;
  shader_ = nullptr;
  return temp;
}
inline ::Proto::Common::ShaderProto* ObjectProto::_internal_mutable_shader() {
  
  if (shader_ == nullptr) {
    auto* p = CreateMaybeMessage<::Proto::Common::ShaderProto>(GetArena());
    shader_ = p;
  }
  return shader_;
}
inline ::Proto::Common::ShaderProto* ObjectProto::mutable_shader() {
  // @@protoc_insertion_point(field_mutable:Proto.Common.ObjectProto.shader)
  return _internal_mutable_shader();
}
inline void ObjectProto::set_allocated_shader(::Proto::Common::ShaderProto* shader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete shader_;
  }
  if (shader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(shader);
    if (message_arena != submessage_arena) {
      shader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, shader, submessage_arena);
    }
    
  } else {
    
  }
  shader_ = shader;
  // @@protoc_insertion_point(field_set_allocated:Proto.Common.ObjectProto.shader)
}

// repeated .Proto.Common.TextureProto texture = 2;
inline int ObjectProto::_internal_texture_size() const {
  return texture_.size();
}
inline int ObjectProto::texture_size() const {
  return _internal_texture_size();
}
inline void ObjectProto::clear_texture() {
  texture_.Clear();
}
inline ::Proto::Common::TextureProto* ObjectProto::mutable_texture(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.Common.ObjectProto.texture)
  return texture_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::TextureProto >*
ObjectProto::mutable_texture() {
  // @@protoc_insertion_point(field_mutable_list:Proto.Common.ObjectProto.texture)
  return &texture_;
}
inline const ::Proto::Common::TextureProto& ObjectProto::_internal_texture(int index) const {
  return texture_.Get(index);
}
inline const ::Proto::Common::TextureProto& ObjectProto::texture(int index) const {
  // @@protoc_insertion_point(field_get:Proto.Common.ObjectProto.texture)
  return _internal_texture(index);
}
inline ::Proto::Common::TextureProto* ObjectProto::_internal_add_texture() {
  return texture_.Add();
}
inline ::Proto::Common::TextureProto* ObjectProto::add_texture() {
  // @@protoc_insertion_point(field_add:Proto.Common.ObjectProto.texture)
  return _internal_add_texture();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Proto::Common::TextureProto >&
ObjectProto::texture() const {
  // @@protoc_insertion_point(field_list:Proto.Common.ObjectProto.texture)
  return texture_;
}

// -------------------------------------------------------------------

// LightProto

// uint32 x = 1;
inline void LightProto::clear_x() {
  x_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::x() const {
  // @@protoc_insertion_point(field_get:Proto.Common.LightProto.x)
  return _internal_x();
}
inline void LightProto::_internal_set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  x_ = value;
}
inline void LightProto::set_x(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Proto.Common.LightProto.x)
}

// uint32 y = 2;
inline void LightProto::clear_y() {
  y_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::y() const {
  // @@protoc_insertion_point(field_get:Proto.Common.LightProto.y)
  return _internal_y();
}
inline void LightProto::_internal_set_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  y_ = value;
}
inline void LightProto::set_y(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Proto.Common.LightProto.y)
}

// uint32 z = 3;
inline void LightProto::clear_z() {
  z_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::_internal_z() const {
  return z_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LightProto::z() const {
  // @@protoc_insertion_point(field_get:Proto.Common.LightProto.z)
  return _internal_z();
}
inline void LightProto::_internal_set_z(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  z_ = value;
}
inline void LightProto::set_z(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Proto.Common.LightProto.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Common
}  // namespace Proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fCommon_2eproto
